# Generated by Django 3.2.18 on 2023-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acd_Patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Abstract')),
                ('claims', models.TextField(blank=True, null=True, verbose_name='Claims')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер патента')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название патента')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('authors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Авторы')),
                ('mpk', models.CharField(blank=True, max_length=255, null=True, verbose_name='МПК')),
            ],
        ),
    ]
