# Generated by Django 3.2.18 on 2023-04-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_patent_dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patents',
            name='asd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search_patent_dev.acd_patents'),
        ),
    ]
